spring:
  data:
    mongodb:
      authentication-database: admin
      username: mongodb
      password: mongodbpw
      database: webservice
      port: 27017
      host: localhost
#      auto-index-creation: true
  rabbitmq:
    addresses: localhost:5672

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8082/eureka}
    fetch-registry: true
    register-with-eureka: true
    enabled: false
  instance:
    preferIpAddress: true

# RabbitMQ
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key