spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: file://C:\Users\flod\IdeaProjects\java-microservices\cloud-config-server\git-cloud-config-repo

server:
  port: 8888
