server:
  port: 8080

spring:
  application:
    name: api-gateway

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8082/eureka}
  instance:
    preferIpAddress: true
