spring:
    # Spring JDBC Properties
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=webservice
    username: postgres
    password: postgrespw

  # Flyway config
  flyway:
    #    enabled: false
    schemas: webservice
    outOfOrder: true
    baseline-version: 0
    baselineOnMigrate: true
    table: schema_history

  security:
    oauth2:
      resource-server:
        opaque-token:
          introspection-uri: http://localhost:8081/auth/realms/flo-dev/protocol/openid-connect/token/introspect
          client-id: FLO_API_SECRET
          client-secret: ofBYMfWcT48VYenq8kh0jzdYegxxSPAZ

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8082/eureka}
  instance:
    preferIpAddress: true

administration:
  endpoint: http://localhost:9091/api
  username: sa-basic-secret
  password: sa-basic-secret