version: '3'

services:
  postgres:
    container_name: postgres
    image: "postgres:15.0"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  rabbitmq:
    container_name: rabbitmq
    image: "3.11-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-discovery-server:
    build:
      context: ./../eureka-discovery-server
      dockerfile: ./../eureka-discovery-server/Dockerfile
    restart: always
    ports:
      - "8082:8082"
    deploy:
      mode: replicated
      replicas: 1


  api-gateway-server:
    build:
      context: ./../api-gateway
      dockerfile: ./../api-gateway/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    networks:
      - spring
    depends_on:
      - eureka-discovery-server

  keycloak-authorization-server:
    build:
      context: ./../keycloak-authorization-server/embedded-keycloak-server
      dockerfile: ./../embedded-keycloak-server/Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      mode: replicated
      replicas: 1

  administration-service:
    build:
      context: ./../administration-service
      dockerfile: ./../administration-service/Dockerfile
    restart: always
    ports:
      - "9091:9091"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      mode: replicated
      replicas: 1

  handler-service:
    build:
      context: ./../handler-service
      dockerfile: ./../handler-service/Dockerfile
    restart: always
    ports:
      - "9093:9093"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    deploy:
      mode: replicated
      replicas: 1