spring:
  application:
    name: eureka-discovery-server
  cloud:
    config:
      enabled: false

server:
  port: 8082

eureka:
  instance:
    hostname: eureka-discovery-server
  client:
    register-with-eureka: false
    fetch-registry: false
