server:
  servlet:
    context-path: /api
  port: 9091
  error:
    include-message: always

spring:
  application:
    name: administration-service
  profiles:
    active: local
  jpa:
    show-sql: true

logging:
  level:
    org:
      springframework:
  #        web: DEBUG
#        hibernate: INFO