spring:
    # Spring JDBC Properties
  datasource:
    #    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=fsa
    username: postgres
    password: postgrespw
  jpa:
    show-sql: true
  rabbitmq:
    addresses: localhost:5672

  security:
    oauth2:
      resource-server:
        opaque-token:
          introspection-uri: http://localhost:8081/auth/realms/flo-dev/protocol/openid-connect/token/introspect
          client-id: FLO_API_SECRET
          client-secret: ofBYMfWcT48VYenq8kh0jzdYegxxSPAZ

  # Flyway config
  flyway:
    #    enabled: false
    schemas: fsa
    outOfOrder: true
    baseline-version: 0
    baselineOnMigrate: true
    table: schema_history

security:
  host: http://localhost:8081/auth/admin/realms/flo-dev

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8082/eureka}
    fetch-registry: true
    register-with-eureka: true
    enabled: false
  instance:
    preferIpAddress: true